# Generated by Django 6.0.1 on 2026-01-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0003_user_created_at_user_created_by_user_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
