# Generated by Django 6.0.7 on 2026-08-30 01:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('tenants', '0004_remove_invitation_unique_pending_tenant_invitation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('khalti', 'Khalti'), ('esewa', 'eSewa')], max_length=32, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox / Test'), ('live', 'Live / Production')], default='sandbox', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['provider'],
            },
        ),
        migrations.RemoveIndex(
            model_name='subscription',
            name='billing_sub_provider_9c8f2e_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='billing_pay_tenant__9b948c_idx',
            old_name='billing_pay_tenant__aaf8ce_idx',
        ),
        migrations.RenameIndex(
            model_name='subscription',
            new_name='billing_sub_tenant__d36cf8_idx',
            old_name='billing_sub_tenant__7e0a6d_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookevent',
            new_name='billing_web_event_t_e3f298_idx',
            old_name='billing_web_event_ty_0b62f4_idx',
        ),
        migrations.RemoveField(
            model_name='price',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='product',
            name='provider',
        ),
        migrations.AddField(
            model_name='checkoutsession',
            name='provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('khalti', 'Khalti'), ('esewa', 'eSewa')], default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_file',
            field=models.FileField(blank=True, upload_to='billing/invoices/'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('khalti', 'Khalti'), ('esewa', 'eSewa')], default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='processing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='billingcustomer',
            name='provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('khalti', 'Khalti'), ('esewa', 'eSewa')], max_length=32),
        ),
        migrations.AlterField(
            model_name='billingcustomer',
            name='provider_customer_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='billingcustomer',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_customers', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='checkoutsession',
            name='mode',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='checkoutsession',
            name='provider_session_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(default='npr', max_length=3),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='provider_invoice_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('khalti', 'Khalti'), ('esewa', 'eSewa')], max_length=32),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider_payment_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='price',
            name='amount',
            field=models.PositiveBigIntegerField(help_text='Amount in the smallest currency unit.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='price',
            name='currency',
            field=models.CharField(default='npr', max_length=3),
        ),
        migrations.AlterField(
            model_name='price',
            name='interval',
            field=models.CharField(choices=[('day', 'Days'), ('week', 'Weeks'), ('month', 'Months'), ('year', 'Years')], default='month', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('khalti', 'Khalti'), ('esewa', 'eSewa')], max_length=32),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='provider_subscription_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('incomplete', 'Incomplete'), ('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past due'), ('canceled', 'Canceled'), ('unpaid', 'Unpaid'), ('paused', 'Paused')], max_length=32),
        ),
        migrations.AlterField(
            model_name='webhookevent',
            name='event_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='webhookevent',
            name='provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('khalti', 'Khalti'), ('esewa', 'eSewa')], max_length=32),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['provider', 'provider_customer_id'], name='billing_sub_provide_c99c6d_idx'),
        ),
        migrations.AddConstraint(
            model_name='billingcustomer',
            constraint=models.UniqueConstraint(fields=('tenant', 'provider'), name='billing_customer_tenant_provider_unique'),
        ),
        migrations.AddConstraint(
            model_name='billingcustomer',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_customer_id'), name='billing_customer_provider_id_unique'),
        ),
        migrations.AddConstraint(
            model_name='checkoutsession',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_session_id'), name='billing_checkout_provider_id_unique'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_invoice_id'), name='billing_invoice_provider_id_unique'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_payment_id'), name='billing_payment_provider_id_unique'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_subscription_id'), name='billing_subscription_provider_id_unique'),
        ),
        migrations.AddConstraint(
            model_name='webhookevent',
            constraint=models.UniqueConstraint(fields=('provider', 'event_id'), name='billing_webhook_provider_event_unique'),
        ),
    ]
