# Generated by Django 6.0.7 on 2026-08-31 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_billing_stripe_fields'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='billingcustomer',
            name='billing_customer_provider_id_unique',
        ),
        migrations.AddField(
            model_name='price',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='billingcustomer',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='billingcustomer',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
