# Generated by Django 6.0.7 on 2026-08-31 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_remove_billingcustomer_billing_customer_provider_id_unique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutsession',
            name='url',
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='hosted_invoice_url',
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_pdf',
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
    ]
